### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by cys01** [cys01/OSSL_group18#1]
앞으로의 프로젝트는 여기서 이야기하게 될 것 같아요! 잘 부탁드려요!

**Comment by JisuShin1** [comment]
네 잘부탁드립니다!
저희 CRUD 가지고 프로젝트를 할텐데 혹시 생각하신 주제 있으신가요?

**Comment by cys01** [comment]
저는 약간 게임에서 나올 것 같은 경매장쪽으로 생각해봤어요

**Comment by JisuShin1** [comment]
그 저는 CRUD해서 할 일 작성하는 작은 노트 기능도 생각했었고 또는 도서관 사서 기능같은 것도 생각해봤는데

**Comment by JisuShin1** [comment]
오 경매장 좋은 것 같아요

**Comment by cys01** [comment]
도서관리도 괜찮은 거 같아요!

**Comment by JisuShin1** [comment]
그러면 각각에 들어갈 함수들 생각해보고 더 괜찮은 걸로 할까요?

**Comment by cys01** [comment]
그런데 저는 게임경매장 같은 경우에는 이름이 비슷한 게 많이 나오고 많은 데이터도 필요할 것 같아서 도서관리가 더 괜찮은 거 같아요

**Comment by JisuShin1** [comment]
아 그런가요? 그러면 도서관리로할까요?

**Comment by JisuShin1** [comment]
도서관리쪽에는 대출 여부 검색, 연체여부 검색, 작가 검색, 예약 여부 검색.. 등이 생각나는데

**Comment by JisuShin1** [comment]
혹시 다른 검색 기능 생각나는거 있으신가요? 책 이름 검색을 빼먹었네여

**Comment by cys01** [comment]
저는 그 책마다 있는 분류체계로 검색하는 것도 괜찮은 거 같다고 생각해요

**Comment by cys01** [comment]
보통 400번대면 수학이나 과학이고 500번대면 기술 같은 책이 나열되어있는 그런거요

**Comment by JisuShin1** [comment]
오 좋은 거 같아요!
그러면 저희가 미리 분류해서 입력해야겠죠?

**Comment by cys01** [comment]
아마 그래야 할꺼긴 한데 그냥 일단은 백의 자리만 맞추면 될꺼 같아요

**Comment by JisuShin1** [comment]
번호 자체를 검색 하는 기능도 있고 각 번호대로 전체적으로 조회하는 것도 만들면 좋을거 같아요

**Comment by cys01** [comment]
그냥 장르? 비슷한 느낌으로 적어서 문자로 검색해도 괜찮아 보여요

**Comment by JisuShin1** [comment]
오 좋은거 같아요

**Comment by JisuShin1** [comment]
아 만약 연체 여부 검색하려면 대출 날짜도 입력해야할거 같은데 너무 복잡할까요?

**Comment by cys01** [comment]
아 괜찮을 거 같아요!

**Comment by cys01** [comment]
저는 둘 다 해도 괜찮을 거 같긴 해요..

**Comment by JisuShin1** [comment]
아 그러면 날짜까지 적고 검색 기능 5개에 create, read, update, delete 함수랑 몇가지 더 넣으면 10개 될거 같은데 검색은 여기서 멈춰도 될거 같아요!

**Comment by cys01** [comment]
그러면 혹시 issue 바꿔서 주제에 대해 더 구체적으로 짜도 괜찮을까요?

**Comment by JisuShin1** [comment]
좋습니다!
