### ISSUE TITLE
Save & Load 함수 만들었습니다!

### ISSUE THREAD

**Issue by cys01** [cys01/OSSL_group18#11]
Create, Update, Delete 함수도 다중 데이터로 받을 수 있도록 수정해주시고, 실행해보셔서 오류 확인해주세요!

**Comment by JisuShin1** [comment]
CUD 다중데이터로 바꾸었습니다! save, load도 확인했습니다.

**Comment by JisuShin1** [comment]
곧 검색함수 2개도 올리겠습니다.
