### ISSUE TITLE
Search 함수 제작 및 오류 수정

### ISSUE THREAD

**Issue by cys01** [cys01/OSSL_group18#12]
대출 가능 여부 탐색 및 연체 여부 탐색 함수 구현 완료하고, Update나 Delete에 있던 while문과 같은 오류들 모두 수정했습니다!

**Comment by cys01** [comment]
평가 내용 중에 협업 평가 중
* Repository PR과 소유자 PR Merge내역
부문이 있기 때문에, 앞으로 남은 검색 기능이나 오류 수정과 같은 내용들은 fork Repository에서 PR로 해주시면 감사하겠습니다!

**Comment by JisuShin1** [comment]
앗 이미 작성했는데 다시 PR로 요청하겠습니다!
