### ISSUE TITLE
기본 파일 및 구조체 초안 생성

### ISSUE THREAD

**Issue by cys01** [cys01/OSSL_group18#7]
C파일과 헤더파일, 구조체 초안 만들었습니다! C 파일에서 index가 main C 파일이고 나머지 books C파일과 헤더파일은 라이브러리입니다. 혹시 사용함에 있어 불편함이 있거나 하는 점은 여기에 comment 달아주시면 감사하겠습니다!

**Comment by JisuShin1** [comment]
네 감사합니다! C,U,D 만들고 issue 새로 생성하겠습니다!
