### ISSUE TITLE
Create, Update, Delete 함수 완성했습니다!

### ISSUE THREAD

**Issue by JisuShin1** [cys01/OSSL_group18#8]

**Comment by JisuShin1** [comment]
함수들 books.c에 작성했고 books.h에도 선언해두었습니다! 확인해주시고 작동이 안되거나 수정할 점 있으면 알려주시길 바랍니다 :)

**Comment by JisuShin1** [comment]
약간의 오류를 확인해서 수정하였습니다!

**Comment by JisuShin1** [comment]
문자열 입력 받는데 getchar를 안해서 scanf가 한번에 일어나는 일이 있었는데 확인을 제대로 하지 못햐서 몰랐었습니다! 그래서 그거 고치고 \n추가했습니다!

**Comment by cys01** [comment]
원래 ^\n으로 해놓아서 scanf가 한번에 일어나지는 않을 것 같았는데 오류가 생겼나요?

**Comment by cys01** [comment]
그러네요 \n을 안 지워주면 오류가 생기네요

**Comment by cys01** [comment]
그러면 혹시 `%[^\n]s`에서 `%s`로 바꾸고 `->`도 `.`으로 바꾼 이유 알려주실 수 있나요!

**Comment by JisuShin1** [comment]
엇 실행하는 과정에서 잠시 바꿔놓는다는게 다시 수정을 안했네요ㅠㅜ .은 다시 ->로 바꿔놓겠습니다!

**Comment by JisuShin1** [comment]
%[^\n]s 해서 공백까지 입력 받으려고 했습니다!
