### ISSUE TITLE
하나 단위로 입력받는 부분까지 오류 수정 완료했습니다!

### ISSUE THREAD

**Issue by cys01** [cys01/OSSL_group18#9]
할 수 있다면 현재까지의 commit을 pull 하셔서 다중 데이터를 관리하는 방식으로 바꿀 수 있으면 좋겠습니다! 수고하셨습니다!

**Comment by cys01** [comment]
아 그리고 혹시 제가 대출 날짜를 년도까지 입력받거나, 대출 가능 여부를 먼저 입력 받아서 대출이 가능한 경우에 자동으로 00000000으로 만드는 코드로 수정해도 괜찮을까요?

**Comment by JisuShin1** [comment]
아 네 괜찮습니다! 수고하셨습니다!
